server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuario
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

appDescription: "plazaleta API"
appVersion: "1.0.0"