server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuario
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: 93fa3e4624676f2e9aa143911118b4547087e9b6e0b6076f2e1027d7a2da2b0a
  expiration: 86400000

appDescription: "plazaleta API"
appVersion: "1.0.0"